### ISSUE TITLE
Plotting more than one taxonomical levels without rerunning all of in Stream 1?

### ISSUE THREAD

**Issue by Dwrgi** [jkzorz/SituSeq#2]
Hi again! Thanks for providing this, it's great! Now that I've got it running, I've got another question:

Is there anyway of plotting more than one taxonomical level without having to go thorugh the whole Stream1 script, especially the long (slow) step to create all the tax.barcodeXX_name_combined.csv files?

Basically, what I'd like to do is to run the Stream 1 script once, but generating two sets of bar charts and bubble plots - onefor Phylum level and and one for Genus level.

It seems to me that the data have already been generated once, so it ought to be possible to just generate some more plots, but I'm not good enough at R to figure out how to make that happen (I've tried lots of things that clearly weren't right :D ). 

Thanks!

**Comment by jkzorz** [comment]
Hi! 

Thanks for testing it out! 
This is a great point. I may try to implement something here, or split the script so that the taxonomic assignment and plotting/analysis are done separately. For the short term, the fix would be to copy the latter part of the script (shown below), and designate a new "taxonomic_level" parameter beforehand (also need to re-specify the sample_number):  

`
taxonomic_level="Genus" #choose from "Phylum" "Class" "Order" "Family" "Genus" 
sample_number=12

#read in newly made csv files 
temp = list.files(pattern="tax.*.csv")
temp_list = list()
for (i in 1:length(temp)) {
    sample = gsub(".csv", "", temp[[i]])
    sample2 = gsub("tax.","",sample)
    new = read.csv(temp[i], header = TRUE) 
    new2 = new %>% filter(Kingdom == "Bacteria") %>% select(all_of(taxonomic_level)) %>% group_by_all() %>% summarise(n = n()) %>% mutate(abund = n/(colSums(as.matrix(n)))*100) %>% select(-n)
    colnames(new2) = c(taxonomic_level, sample2)
    temp_list[[length(temp_list) + 1]] <- new2 }


#merge all data frames in list
tax_df = temp_list %>% reduce(full_join, by=taxonomic_level)

#write summary csv of taxonomic level 
write.csv(tax_df, paste0(taxonomic_level,"_summary.csv"))

#convert data to long format
tax_df_long = tax_df %>% pivot_longer(!taxonomic_level, names_to = "Sample", values_to = "Abundance")

#colour scheme for bubble plot
colours = colorRampPalette(c("#2F4858", "#33658A", "#86BBD8", "#830689", "#F5A614", "#F26419", "#BB3551",  "#C1D7AE", "#68AC5D", "#EBDDAD"))(sample_number)

#remove "_combined" from sample name
tax_df_long$Sample = gsub("_combined","",tax_df_long$Sample)

#bubble plot
xx = ggplot(tax_df_long, aes(x = Sample, y = reorder(get(taxonomic_level), desc(get(taxonomic_level))))) + geom_point(aes(colour = Sample, size= Abundance), alpha = 0.7) +theme(legend.key = element_blank(), legend.title = element_text(size = 10), panel.border = element_rect(fill = NA, colour = "grey80"), axis.text.y = element_text(size = 7), axis.text.x = element_text(size = 7, angle = 90, vjust = 0.3, hjust =1), panel.background = element_blank(), panel.grid.major = element_line(colour = "grey94")) + scale_radius(range=c(1,8), breaks = c(1,10,30,50)) + labs(x = "", y = "", colour = taxonomic_level) + scale_colour_manual(values = colours) + guides(colour = "none")
xx

#save bubble plot
ggsave(paste0("bubble_plot_",taxonomic_level,".png"), height = 6, width = 5.5)

#select top 10 most abundant taxa, based on maximum abundance in data set
tax_df$max = apply(tax_df[,2:ncol(tax_df)], 1, FUN = max, na.rm = TRUE)
tax_df2 <- tax_df[order(-tax_df$max),][1:10,]
 
#colour scheme for bar plot
colours = c("#2F4858", "#33658A", "#86BBD8", "#830689", "#F5A614", "#F26419", "#BB3551",  "#C1D7AE", "#68AC5D", "#EBDDAD")

#convert data to long format
tax_df2_long = tax_df2 %>% select(-max) %>% pivot_longer(!taxonomic_level, names_to = "Sample", values_to = "Abundance")

#remove "_combined" from sample name
tax_df2_long$Sample = gsub("_combined","",tax_df2_long$Sample)

#bar plot of most abundant phyla
gg = ggplot(tax_df2_long, aes(x = Sample, y = Abundance)) + geom_bar(aes(fill = get(taxonomic_level)), colour = "black", position = "stack", stat = "identity") + scale_fill_manual(values = colours) + labs(x = "", y = "Relative Abundance (%)", fill = taxonomic_level) + theme(panel.background = element_blank(), panel.border = element_rect(fill =NA, colour = "black"), axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.3), legend.key = element_blank()) + scale_y_continuous(limits = c(0,100), expand = c(0,0))
gg

#save plot
ggsave(paste0("bar_plot_top_",taxonomic_level,".png"), height = 6, width = 5)
`

**Comment by Dwrgi** [comment]
Great, thanks!  I'll try it out tomorrow once this has finished running. 

I did attempt to do something similar but kept getting an error message with something about Genus/n missing. But I ahve the feeling it was more down me lacking skills in R than anything.

**Comment by Dwrgi** [comment]
Hi, That bit of code worked beautifully! For now I just put it in a different file but  it was very fast! :) Thank you!

I noticed that as I went down in taxonomical level, the labels on the y-axis of the bubble chart started to overlap more and more.
